pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://jitpack.io'
        }
        maven {
            url 'https://oss.sonatype.org/content/repositories/releases'
        }
        // Required for ffmpeg-kit
        maven {
            url 'https://packages.arthenica.com/maven/public'
        }
    }
}

rootProject.name = "LiveMonitor"
include ':app'
